# This file was generated by GoReleaser. DO NOT EDIT.
cask "cfgaudit" do
  version "1.12.1"

  on_macos do
    on_intel do
      sha256 "c17f6098d8a88c86cc66ac4d55467976ce0e0efca9f4426834f9690f858a168e"
      url "https://github.com/cfgaudit/cfgaudit/releases/download/v#{version}/cfgaudit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e54e8f7753ccf6ebbc18ca3e92250801e2417d1144ddfcfc2a4afd92c5d77546"
      url "https://github.com/cfgaudit/cfgaudit/releases/download/v#{version}/cfgaudit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "427b93b19c5c3311f5e1fa913393b582b20f2eb4694b987601860b416da5c82c"
      url "https://github.com/cfgaudit/cfgaudit/releases/download/v#{version}/cfgaudit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a0f3177ae47019fba4c893ec5721abab32fb826feba02a430a3b8173f6edc448"
      url "https://github.com/cfgaudit/cfgaudit/releases/download/v#{version}/cfgaudit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cfgaudit"
  desc "Security auditor for AI-agent configuration files"
  homepage "https://github.com/cfgaudit/cfgaudit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cfgaudit"

  # No zap stanza required

end
