# This file was generated by GoReleaser. DO NOT EDIT.
cask "cfgaudit" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "1b5affdd2e5ba0136ea5c13c79979f863328db247dda5432d13718dbe686dad9"
      url "https://github.com/cfgaudit/cfgaudit/releases/download/v#{version}/cfgaudit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "55a1c1f1a2bf4873c21cc0ef2cf1330264437def4072dd9af343615d908363ef"
      url "https://github.com/cfgaudit/cfgaudit/releases/download/v#{version}/cfgaudit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c1b1f230800a2eac92ccfc2db44b954fff67d0d7adad7811bbdae8a8126fbc46"
      url "https://github.com/cfgaudit/cfgaudit/releases/download/v#{version}/cfgaudit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ffe9533441d1a93eb00b7f19cd7eecb28571ac0c33d9b4c15e97f50684f5aefb"
      url "https://github.com/cfgaudit/cfgaudit/releases/download/v#{version}/cfgaudit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cfgaudit"
  desc "Security auditor for AI-agent configuration files"
  homepage "https://github.com/cfgaudit/cfgaudit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cfgaudit"

  # No zap stanza required

end
