# This file was generated by GoReleaser. DO NOT EDIT.
cask "cfgaudit" do
  version "1.9.0"

  on_macos do
    on_intel do
      sha256 "635dca5efad1c37bb936be2188c4dbb172a1498f3f3373e2187d2234e3002889"
      url "https://github.com/cfgaudit/cfgaudit/releases/download/v#{version}/cfgaudit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5f70298d535defebe54b196da370f16ac8121471ba1c6b781d5ba9315901a120"
      url "https://github.com/cfgaudit/cfgaudit/releases/download/v#{version}/cfgaudit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8f15ea19f65df38f0e0f4d53d1bd7ab11818da9c7b6a46e7da3d8e30c9d26f6a"
      url "https://github.com/cfgaudit/cfgaudit/releases/download/v#{version}/cfgaudit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7ed86d375eeea7fc1b219ebfeb59531e03cc840c3f2cff44868cad9bf53663b6"
      url "https://github.com/cfgaudit/cfgaudit/releases/download/v#{version}/cfgaudit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cfgaudit"
  desc "Security auditor for AI-agent configuration files"
  homepage "https://github.com/cfgaudit/cfgaudit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cfgaudit"

  # No zap stanza required

end
